google_maps:
  base_url: https://www.google.com/maps
  pagination:
    load_more_button: '[data-value=''Show more results'']'
    scroll_container: .m6QErb
    scroll_pause: 2
  search_settings:
    max_scroll_attempts: 10
    scroll_pause_time: 2
    wait_for_results: 5
  search_url: https://www.google.com/maps/search/{query}
  selectors:
    business_address: .W4Efsd, .fontBodyMedium, .W4Efsd::text
    business_category: .fontBodyMedium, .W4Efsd, .fontBodyMedium::text
    business_listing: '[data-result-index], .Nv2PK, .VkpGBb, .lI9IFe'
    business_name: h3, .fontHeadlineSmall, .qBF1Pd, .fontHeadlineSmall::text
    business_phone: a[href^='tel:']::attr(href), .fontBodyMedium a[href^='tel:']::attr(href)
    business_rating: .fontDisplayLarge, .MW4etd, .fontDisplayLarge::text
    business_review_count: .fontBodyMedium, .UY7F9, .fontBodyMedium::text
    business_website: a[href^='http']::attr(href), .fontBodyMedium a[href^='http']::attr(href)
search_queries:
- keywords: Restaurant
  location: Florida
  name: Restaurant in Florida
settings:
  concurrent_requests: 16
  concurrent_requests_per_domain: 8
  delay: 2
  download_delay: 1
  download_timeout: 30
  max_pages: 10
  respect_robots: false
  retry_http_codes:
  - 500
  - 502
  - 503
  - 504
  - 408
  - 429
  retry_times: 3
  user_agent: LeadTool/1.0 (+https://leadtool.example.com)
